<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (Schema::hasTable('registers') && !Schema::hasTable('students')) {
            Schema::rename('registers', 'students');
        }

        if (!Schema::hasTable('students')) {
            return;
        }

        Schema::table('students', function (Blueprint $table) {
            // new student profile fields
            $table->string('nickname')->nullable()->after('name');
            $table->string('address')->nullable()->after('email');
            $table->string('facebook_acc_name')->nullable()->after('address');
            $table->string('telegram_username')->nullable()->after('viber_phone');
            $table->string('native_town')->nullable()->after('city');
            $table->string('religious_status')->nullable()->after('native_town');
            $table->string('race')->nullable()->after('religious_status');

            // login credentials (generated by the app)
            $table->string('username', 50)->nullable()->unique()->after('image');
            $table->string('password', 255)->nullable()->after('username');
        });

        // course / section now live in student_enrollments, so they are optional here
        DB::statement('ALTER TABLE `students` MODIFY `course_id` BIGINT UNSIGNED NULL');
        DB::statement('ALTER TABLE `students` MODIFY `section_id` BIGINT UNSIGNED NULL');

        // allow partially filled profiles
        foreach (['register_date', 'enroll_date', 'father_name', 'mother_name', 'viber_phone', 'email', 'township', 'date_of_birth', 'nrc', 'education', 'image'] as $column) {
            DB::statement("ALTER TABLE `students` MODIFY `$column` VARCHAR(191) NULL");
        }
        DB::statement('ALTER TABLE `students` MODIFY `phone` VARCHAR(20) NULL');

        // gender: integer (0/1) -> readable string
        DB::statement("ALTER TABLE `students` ADD COLUMN `gender_new` VARCHAR(20) NULL");
        DB::statement("UPDATE `students` SET `gender_new` = CASE WHEN `gender` = 1 THEN 'male' WHEN `gender` = 0 THEN 'female' ELSE NULL END");
        DB::statement('ALTER TABLE `students` DROP COLUMN `gender`');
        DB::statement("ALTER TABLE `students` CHANGE `gender_new` `gender` VARCHAR(20) NULL");

        // status: integer (0/1) -> active / inactive
        DB::statement("ALTER TABLE `students` ADD COLUMN `status_new` VARCHAR(20) NOT NULL DEFAULT 'inactive'");
        DB::statement("UPDATE `students` SET `status_new` = CASE WHEN `status` = 1 THEN 'active' ELSE 'inactive' END");
        DB::statement('ALTER TABLE `students` DROP COLUMN `status`');
        DB::statement("ALTER TABLE `students` CHANGE `status_new` `status` VARCHAR(20) NOT NULL DEFAULT 'inactive'");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (!Schema::hasTable('students')) {
            return;
        }

        DB::statement("ALTER TABLE `students` ADD COLUMN `status_old` TINYINT NOT NULL DEFAULT 0");
        DB::statement("UPDATE `students` SET `status_old` = CASE WHEN `status` = 'active' THEN 1 ELSE 0 END");
        DB::statement('ALTER TABLE `students` DROP COLUMN `status`');
        DB::statement('ALTER TABLE `students` CHANGE `status_old` `status` TINYINT NOT NULL DEFAULT 0');

        DB::statement("ALTER TABLE `students` ADD COLUMN `gender_old` TINYINT NULL");
        DB::statement("UPDATE `students` SET `gender_old` = CASE WHEN `gender` = 'male' THEN 1 WHEN `gender` = 'female' THEN 0 ELSE NULL END");
        DB::statement('ALTER TABLE `students` DROP COLUMN `gender`');
        DB::statement('ALTER TABLE `students` CHANGE `gender_old` `gender` TINYINT NULL');

        DB::statement('ALTER TABLE `students` MODIFY `phone` VARCHAR(15) NOT NULL');
        DB::statement('ALTER TABLE `students` MODIFY `course_id` BIGINT UNSIGNED NOT NULL');
        DB::statement('ALTER TABLE `students` MODIFY `section_id` BIGINT UNSIGNED NOT NULL');

        Schema::table('students', function (Blueprint $table) {
            $table->dropUnique(['username']);
            $table->dropColumn([
                'nickname',
                'address',
                'facebook_acc_name',
                'telegram_username',
                'native_town',
                'religious_status',
                'race',
                'username',
                'password',
            ]);
        });

        Schema::rename('students', 'registers');
    }
};
